version: "3.9"

services:
  fruit-api:
    build: .
    container_name: fruit-api-h2
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/fruitdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: true
    volumes:
      - h2data:/app/data

volumes:
  h2data:
